feat(ledger): Add /volumes endpoint with OOT and PIT filters
formancehq/stack pull request #1407
Opened 2024-04-09 17:06 UTC by Dav-14

2024-04-09 17:14 UTC, Dav-14 commented on components/ledger/internal/storage/ledgerstore/utils.go
> +
there is still comment ?

2024-04-10 08:36 UTC, gfyrag commented on components/ledger/openapi/v2.yaml
> +        input:
Use big int for inputs, outputs, and balances please.

2024-04-10 08:41 UTC, gfyrag requested changes
You need to use bigint instead of int64 in the openapi spec.

2024-04-10 13:09 UTC, gfyrag approved these changes

2024-04-10 15:54 UTC, paul-nicolas approved these changes

2024-04-12 07:07 UTC, merged