fix(operator): ingressClassName prior the deprecated annotations
formancehq/stack pull request #1605
Opened 2024-07-10 11:59 UTC by Dav-14

2024-07-10 15:21 UTC, lucasfcnunes requested changes

2024-07-10 15:21 UTC, lucasfcnunes commented on components/operator/helm/crds/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_gateways.formance.com.yaml
> +                    description: Custom Ingress class to use
I don't think the word custom is needed. Every `Ingress` in k8s need an `IngressClass` to point to. Sometimes the cluster has a default one sometimes it doesn't.

2024-07-10 15:21 UTC, lucasfcnunes commented on components/operator/docs/09-Configuration reference/02-Custom Resource Definitions.md
> +| `ingressClassName` _string_ | Custom Ingress class to use |  |  |
Vide comment on `components/operator/helm/crds/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_gateways.formance.com.yaml`

2024-07-10 15:21 UTC, lucasfcnunes commented on components/operator/config/crd/bases/formance.com_gateways.yaml
> +                    description: Custom Ingress class to use
Vide comment on `components/operator/helm/crds/templates/crds/apiextensions.k8s.io_v1_customresourcedefinition_gateways.formance.com.yaml`

2024-07-15 09:09 UTC, gfyrag approved these changes

2024-07-15 09:30 UTC, merged