fix(ledger): Decode parameters in the ledger
formancehq/stack pull request #1616
Opened 2024-07-22 19:20 UTC by flemzord

2024-07-26 13:37 UTC, Dav-14 approved these changes

2024-08-29 11:30 UTC, gfyrag reviewed
Use 404 instead of 500 on url parsing error (or any 4XX i don't care).

2024-08-29 11:30 UTC, gfyrag requested changes
Use 404 instead of 500 on url parsing error (or any 4XX i don't care).

2024-09-03 09:49 UTC, gfyrag approved these changes
WithDetails is redundant. The error message will be duplicated in the response.

2024-09-03 09:57 UTC, merged